### ISSUE TITLE
タスク一覧が開けない

### ISSUE THREAD

**Issue by Nishida-Satoshi** [enpitut2018/task_driver#120]
タスクの一覧画面が開きません。

**Comment by itumizu** [comment]
グループを削除した際に、子グループ・子タスクを同時に削除していませんでした。
そのため、タスク一覧ページで、タスクが存在しない親グループを参照していたため、エラーとなっていました。
コミット 9928751c2b0a510847fbd9fee9cfc992668cb822 で修正しました。
