### ISSUE TITLE
TaskDriver -> Folivoraへの名前の変更

### ISSUE THREAD

**Issue by Kunado** [enpitut2018/task_driver#188]
# 追加機能
* タイミングを見つつ名前を変更する
## 変更箇所
* リポジトリ名
   + ローカルにある変更を済ませた上でリポジトリ名を全て変える
* herokuのドメイン
   + rails側に`api.folivora.sukiyaki.party`を、nuxt側に`folivora.sukiyaki.party`を向ける
* `nuxt.config.js`内のサイト名

**Comment by itumizu** [comment]
nuxt.config.jsは変更されているので、閉じます
