### ISSUE TITLE
しょきとうろくして、プロジェクトGeneralをひらくとエラーになる

### ISSUE THREAD

**Issue by kyonmm** [enpitut2018/task_driver#272]
![default](https://user-images.githubusercontent.com/839274/51297666-8d3abf00-1a64-11e9-8005-bb8d3eeb9a8e.PNG)

**Comment by itumizu** [comment]
ご指摘ありがとうございます。
[こちら](https://github.com/enpitut2018/task_driver_frontend/pull/142) で修正しました.
