### ISSUE TITLE
先祖グループの生成ができない

### ISSUE THREAD

**Issue by Kunado** [enpitut2018/task_driver#81]
既存のグループの子としてしかグループを作成できないためgeneralの子孫のグループしか作れない

**Comment by Kunado** [comment]
グループ作成時に親グループの選択が必須なため。

**Comment by itumizu** [comment]
コミット d7a11ce8cae874c08b26a9015569c0f6beb07991 で、グループ選択時に空値を選択できるようにしておいたので、これで修正されたということで大丈夫ですかね...?

**Comment by Kunado** [comment]
大丈夫です！
